const programs = {
  prog1: {
    title: "Program 1",
    text: "Program 1 contains 1a for counting lines, spaces, words, and characters, and 1b for validating the grammar using Lex and Yacc.",
    items: [
      {
        id: "1a",
        title: "Program 1A",
        description: "Count number of lines, spaces, words, and characters from a paragraph.",
        files: [{ label: "prog.l", path: "programs/1a/prog.l", language: "lex" }],
        input: "programs/1a/input.txt",
        run: "lex prog.l\ngcc lex.yy.c -o output -ll\n./output"
      },
      {
        id: "1b",
        title: "Program 1B",
        description: "Validate strings generated by the grammar a^n b^n b^m c^m.",
        files: [
          { label: "prog.l", path: "programs/1b/prog.l", language: "lex" },
          { label: "prog.y", path: "programs/1b/prog.y", language: "yacc" }
        ],
        input: "programs/1b/input.txt",
        run: "lex prog.l\nyacc -d prog.y\ngcc lex.yy.c y.tab.c -o parser -ll\n./parser"
      }
    ]
  },
  prog2: {
    title: "Program 2",
    text: "Program 2 contains number classification using Lex and arithmetic expression evaluation using Lex and Yacc.",
    items: [
      {
        id: "2a",
        title: "Program 2A",
        description: "Count positive integers, negative integers, positive fractions, and negative fractions.",
        files: [{ label: "prog.l", path: "programs/2a/prog.l", language: "lex" }],
        input: "programs/2a/input.txt",
        run: "lex prog.l\ngcc lex.yy.c -o output -ll\n./output"
      },
      {
        id: "2b",
        title: "Program 2B",
        description: "Evaluate arithmetic expressions with operator precedence and unary minus.",
        files: [
          { label: "prog.l", path: "programs/2b/prog.l", language: "lex" },
          { label: "prog.y", path: "programs/2b/prog.y", language: "yacc" }
        ],
        input: "programs/2b/input.txt",
        run: "lex prog.l\nyacc -d prog.y\ngcc lex.yy.c y.tab.c -o parser -ll\n./parser"
      }
    ]
  },
  prog3: {
    title: "Program 3",
    text: "Program 3 contains nested for-loop validation and function syntax validation.",
    items: [
      {
        id: "3a",
        title: "Program 3A",
        description: "Check whether the input contains at least three nested for loops.",
        files: [
          { label: "prog.l", path: "programs/3a/prog.l", language: "lex" },
          { label: "prog.y", path: "programs/3a/prog.y", language: "yacc" }
        ],
        input: "programs/3a/input.txt",
        run: "lex prog.l\nyacc -d prog.y\ngcc lex.yy.c y.tab.c -o parser -ll\n./parser"
      },
      {
        id: "3b",
        title: "Program 3B",
        description: "Check whether a C-like function is syntactically correct.",
        files: [
          { label: "prog.l", path: "programs/3b/prog.l", language: "lex" },
          { label: "prog.y", path: "programs/3b/prog.y", language: "yacc" }
        ],
        input: "programs/3b/input.txt",
        run: "lex prog.l\nyacc -d prog.y\ngcc lex.yy.c y.tab.c -o parser -ll\n./parser"
      }
    ]
  },
  prog4: {
    title: "Program 4",
    text: "Program 4 generates quadruple, triple, and three-address code for an assignment expression.",
    items: [
      {
        id: "4",
        title: "Program 4",
        description: "Generate intermediate code forms for arithmetic expressions.",
        files: [
          { label: "prog.l", path: "programs/4/prog.l", language: "lex" },
          { label: "prog.y", path: "programs/4/prog.y", language: "yacc" }
        ],
        input: "programs/4/input.txt",
        run: "lex prog.l\nyacc -d prog.y\ngcc lex.yy.c y.tab.c -o parser -ll\n./parser"
      }
    ]
  },
  prog5: {
    title: "Program 5",
    text: "Program 5 translates a small C-like input into simple assembly-style output.",
    items: [
      {
        id: "5",
        title: "Program 5",
        description: "Generate simple target code from declarations, assignment, addition, and printf.",
        files: [
          { label: "prog.l", path: "programs/5/prog.l", language: "lex" },
          { label: "prog.y", path: "programs/5/prog.y", language: "yacc" }
        ],
        input: "programs/5/input.txt",
        run: "lex prog.l\nyacc -d prog.y\ngcc lex.yy.c y.tab.c -o parser -ll\n./parser"
      }
    ]
  }
};

const cache = new Map();
const container = document.querySelector("#programContainer");
const title = document.querySelector("#programTitle");
const text = document.querySelector("#programText");
const tabs = document.querySelectorAll(".tab");
const toast = document.querySelector("#toast");

async function loadText(path) {
  if (cache.has(path)) return cache.get(path);
  const response = await fetch(path);
  if (!response.ok) {
    throw new Error(`Could not load ${path}`);
  }
  const value = await response.text();
  cache.set(path, value.trimEnd());
  return value.trimEnd();
}

function escapeHtml(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function block(label, content, type = "text") {
  const id = crypto.randomUUID();
  return `
    <div class="block">
      <div class="block-title">
        <h4>${label}</h4>
        <button class="copy-btn" data-copy-id="${id}">Copy</button>
      </div>
      <pre><code id="${id}" class="language-${type}">${escapeHtml(content)}</code></pre>
    </div>
  `;
}

async function renderProgram(key) {
  const program = programs[key];
  title.textContent = program.title;
  text.textContent = program.text;
  container.innerHTML = "";

  try {
    const cards = await Promise.all(program.items.map(async (item) => {
      const fileBlocks = await Promise.all(item.files.map(async (file) => {
        const content = await loadText(file.path);
        return block(file.label, content, file.language);
      }));
      const sampleInput = await loadText(item.input);
      return `
        <article class="program-card">
          <div class="card-head">
            <div>
              <h3>${item.title}</h3>
              <p>${item.description}</p>
            </div>
            <span class="tag">${item.id}</span>
          </div>
          ${fileBlocks.join("")}
          ${block("Sample input.txt", sampleInput, "text")}
          ${block("Ubuntu commands to run", item.run, "bash")}
        </article>
      `;
    }));
    container.innerHTML = cards.join("");
  } catch (error) {
    container.innerHTML = `<div class="empty">${escapeHtml(error.message)}</div>`;
  }
}

async function copyText(id, button) {
  const node = document.getElementById(id);
  if (!node) return;
  await navigator.clipboard.writeText(node.textContent);
  button.textContent = "Copied";
  toast.classList.add("show");
  window.setTimeout(() => {
    button.textContent = "Copy";
    toast.classList.remove("show");
  }, 1000);
}

tabs.forEach((tab) => {
  tab.addEventListener("click", () => {
    tabs.forEach((item) => item.classList.remove("active"));
    tab.classList.add("active");
    renderProgram(tab.dataset.program);
  });
});

container.addEventListener("click", (event) => {
  const button = event.target.closest("[data-copy-id]");
  if (button) {
    copyText(button.dataset.copyId, button);
  }
});

renderProgram("prog1");
